DROP TABLE IF EXISTS form;
DROP TABLE IF EXISTS primes;

CREATE TABLE form (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    num TEXT NOT NULL,
    options TEXT NOT NULL
);

CREATE TABLE primes(
    num INTEGER NOT NULL,
    prime INTEGER NOT NULL
);